// <auto-generated />
using System;
using AutoRepairShop.Infrastructure.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRepairShop.Infrastructure.Repository.Migrations
{
    [DbContext(typeof(AutoRepairShopDbContext))]
    partial class AutoRepairShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AutoRepairShop.Domain.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateNumbers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StateNumbers")
                        .IsUnique();

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("14697994-81cd-4cc6-8883-be08faa58e1c"),
                            Brand = "Audi",
                            Engine = 0,
                            Model = "TT",
                            StateNumbers = "А047ЕВ66"
                        },
                        new
                        {
                            Id = new Guid("53df9d76-1da1-4fe9-91a3-38ca179c1841"),
                            Brand = "Toyota",
                            Engine = 0,
                            Model = "Mark 2",
                            StateNumbers = "А002АС"
                        },
                        new
                        {
                            Id = new Guid("742784a0-70c0-4004-820a-22b2c2670945"),
                            Brand = "Opel",
                            Engine = 1,
                            Model = "Astra",
                            StateNumbers = "М033ЕЕ"
                        });
                });

            modelBuilder.Entity("AutoRepairShop.Domain.Models.CarWorkHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CarId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InWork")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OutWork")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TypeOfWorkId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("TypeOfWorkId");

                    b.ToTable("CarWorkHistories");
                });

            modelBuilder.Entity("AutoRepairShop.Domain.Models.TypeOfWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Engine")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypeOfWorks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dca90b74-0b77-47a0-88e9-141cfdb0b748"),
                            Engine = 0,
                            Name = "Замена свечей зажигания"
                        },
                        new
                        {
                            Id = new Guid("d1414603-ea48-4bd4-b5bc-cb1d80994bf1"),
                            Engine = 1,
                            Name = "Замена свечей накаливания"
                        },
                        new
                        {
                            Id = new Guid("8989a114-77f2-4af5-8e6c-a04980a691a5"),
                            Engine = 0,
                            Name = "Проверка компрессии в цилиндрах"
                        },
                        new
                        {
                            Id = new Guid("dbb5e317-e55f-4b84-ac7a-d6c8c43213d3"),
                            Engine = 1,
                            Name = "Проверка компрессии в цилиндрах"
                        });
                });

            modelBuilder.Entity("AutoRepairShop.Domain.Models.CarWorkHistory", b =>
                {
                    b.HasOne("AutoRepairShop.Domain.Models.Car", "Car")
                        .WithMany("WorkHistory")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoRepairShop.Domain.Models.TypeOfWork", "TypeOfWork")
                        .WithMany("WorkHistory")
                        .HasForeignKey("TypeOfWorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("TypeOfWork");
                });

            modelBuilder.Entity("AutoRepairShop.Domain.Models.Car", b =>
                {
                    b.Navigation("WorkHistory");
                });

            modelBuilder.Entity("AutoRepairShop.Domain.Models.TypeOfWork", b =>
                {
                    b.Navigation("WorkHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
